version: "3.8"
services:
  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
    profiles:
      - new
      - renew

  cerbot_new:
    image: certbot/certbot:latest
    container_name: certbot_new
    volumes:
      - ./html/:/tmp/html/
      - ./letsencrypt/:/etc/letsencrypt/
    command: "certonly --agree-tos -v --webroot -w /tmp/html/ -m ${CERTBOT_EMAIL} -d ${CERTBOT_DOMAIN}"
    depends_on:
      - web
    profiles:
      - new

  cerbot_renew:
    image: certbot/certbot:latest
    container_name: certbot_renew
    volumes:
      - ./html/:/tmp/html/
      - ./letsencrypt/:/etc/letsencrypt/
    command: "renew -v"
    depends_on:
      - web
    profiles:
      - renew

